/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-tint': '#c19cff',
        'error': '#ff6e84',
        'surface-dim': '#0e0e0e',
        'surface-container-lowest': '#000000',
        'on-primary-fixed-variant': '#3c0080',
        'on-primary-fixed': '#000000',
        'surface-container-low': '#131313',
        'secondary': '#ff7441',
        'on-primary-container': '#300069',
        'outline-variant': '#484847',
        'primary-dim': '#9146ff',
        'primary-fixed-dim': '#ab78ff',
        'inverse-on-surface': '#565555',
        'on-primary': '#ffffff',
        'secondary-fixed': '#ffc4b1',
        'on-secondary-container': '#fff6f3',
        'background': '#0e0e0e',
        'primary-container': '#b68aff',
        'surface-container': '#1a1a1a',
        'tertiary': '#ff98ae',
        'tertiary-dim': '#f27794',
        'on-tertiary-container': '#5a0023',
        'on-secondary': '#410f00',
        'error-dim': '#d73357',
        'surface-variant': '#262626',
        'tertiary-container': '#ff819f',
        'on-error-container': '#ffb2b9',
        'on-secondary-fixed-variant': '#932d00',
        'secondary-container': '#ab3600',
        'tertiary-fixed-dim': '#f87c99',
        'secondary-dim': '#ff7441',
        'on-tertiary': '#6a0a2d',
        'on-secondary-fixed': '#631b00',
        'primary': '#c19cff',
        'inverse-primary': '#7d00fc',
        'tertiary-fixed': '#ff8fa8',
        'on-surface': '#ffffff',
        'secondary-fixed-dim': '#ffb197',
        'surface-container-high': '#20201f',
        'surface-bright': '#2c2c2c',
        'on-surface-variant': '#adaaaa',
        'on-error': '#490013',
        'error-container': '#a70138',
        'outline': '#767575',
        'surface-container-highest': '#262626',
        'surface': '#0e0e0e',
        'primary-fixed': '#b68aff',
        'inverse-surface': '#fcf9f8',
        'on-background': '#ffffff',
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        label: ['Inter', 'system-ui', 'sans-serif'],
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
